version: '3'
services:
  minio:
    image: minio/minio:RELEASE.2020-09-26T03-44-56Z
    environment:
      - MINIO_REGION=us-east-1
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=password
    ports:
      - 9000:9000
    command: minio server /data